const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94728110445"
const SESSION_ID = "PRABATH-MD~gTkWkAYT#IHi4bMJvMTdss4B_29qJwgOBRn8uJoBpbMK8OnBL4Ng"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
